version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  airflow:
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        - AIRFLOW__CORE__EXECUTOR: LocalExecutor
        - AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
        - AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
        - _PIP_ADDITIONAL_REQUIREMENTS: apache-airflow-providers-postgres
        - AIRFLOW_UID: '50000'
        - AIRFLOW__API__AUTH_BACKEND: airflow.api.auth.backend.basic_auth
        # Admin user creation environment variables
        - AIRFLOW_USER_ADMIN_USERNAME: admin
        - AIRFLOW_USER_ADMIN_PASSWORD: admin_password
        - AIRFLOW_USER_ADMIN_FIRSTNAME: Admin
        - AIRFLOW_USER_ADMIN_LASTNAME: User
        - AIRFLOW_USER_ADMIN_ROLE: Admin
        - AIRFLOW_USER_ADMIN_EMAIL: admin@example.com
      ports:
        - "8080:8080"
      volumes:
        - airflow_dags:/usr/local/airflow/dags
        - airflow_logs:/usr/local/airflow/logs
      depends_on:
        - db
      

volumes:
  db_data:
  airflow_dags:
  airflow_logs: