# Start with the Apache Airflow base image
FROM apache/airflow:latest-python3.8

# Switch to the root user to install additional dependencies
USER root

# Set the AIRFLOW_HOME environment variable
ENV AIRFLOW_HOME=/opt/airflow

# Add your DAGs, ETL scripts, and DB connection scripts
ADD dags /opt/airflow/dags
ADD etl.py /opt/airflow/etl.py
ADD config/connect_db.py /opt/airflow/config/connect_db.py

# Copy your requirements file and install the required Python dependencies
COPY requirements.txt .
RUN pip install --upgrade pip && \
    pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org -r requirements.txt



# Switch back to the `airflow` user for security
USER ${AIRFLOW_UID}

# The command to start Airflow
CMD ["airflow", "webserver"]
