version: "2.1"
services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /data/postgres-data
    volumes:
      - postgres-data:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    # entrypoint: /bin/bash -c "airflow db upgrade && airflow scheduler"
    command: scheduler
    restart: on-failure
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8794:8793"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./airflow-logs:/opt/airflow/logs
      - ./scripts:/opt/airflow/scripts

  webserver:
    hostname: webserver
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ./scripts/airflow-entrypoint.sh
    command: webserver
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    # volumes:
    #   - ./dags:/opt/airflow/dags
    #   - ./airflow-logs:/opt/airflow/logs
    #   - ./scripts:/opt/airflow/scripts
    ports:
      - "8080:8080"
volumes:
  postgres-data: